apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
      - name: class-container
        image:  k8s.gcr.io/busybox
        ports:
        - containerPort: 8888
        command: ["sh", "-c"]
        args:
        - 'while true; do 
            printf "HTTP/1.1 200 OK\nContent-Type: text/html; charset=UTF-8\n\nThis is class project in DigitalOcean!" | nc -l -p 8080;
          done;'
       
      