apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
      - name: class-container
        image:  index.docker.io/away907/class-repo:latest
        ports:
        - containerPort: 8080
        
       
      